### ISSUE TITLE
Error Using v0.15.1

### ISSUE THREAD

**Issue by vishyapps** [LeonardLaszlo/nw.js-armv7-binaries#1]
Hi @LeonardLaszlo ,

I have tested on v0.15.1. (nwjs-v0.15.1-linux-armv7.tar.gz)

ENV: ODROID XU4 running Official Odroid Ubuntu release (14.04)

Upon extracting, the file nw shows as "shared library". 

terminal command "./nw" executed from the folder, throws this error: 
"error while loading shared libraries: libffmpeg.so: cannot open shared object file: No such file or directory".

I have copied libffmpeg.so from libs folder and pasted in the root directory. The sam error prevails. 

Also noted that the file / directory structure is different from the 12.0 and 12.2 releases. Hope that is not the issue.

**Comment by LeonardLaszlo** [comment]
@vishyapps After you extract the archive copy the files from the lib directory to /usr/lib. This way v0.15.1 works on my XU4 device with ubuntu 14.04.

[SDK flavor: has builtin support for DevTools and NaCl plugins. SDK flavor has the same capabilities as the builds before 0.13.0](http://docs.nwjs.io/en/latest/For%20Users/Advanced/Build%20Flavors/)
