### ISSUE TITLE
armv6 raspberry pi zero build

### ISSUE THREAD

**Issue by Zhairgling** [LeonardLaszlo/nw.js-armv7-binaries#10]
Hi @LeonardLaszlo ,

I'm trying to build nw.js for arm6. But I don't achive this. Is there any raison that make that can't find any recent prebuilt version on armv6 build?

**Comment by LeonardLaszlo** [comment]
The ARM architecture is not supported officially. Probably there was no enthuziast to spend lots of hours working on it...
