### ISSUE TITLE
Build nwjs from arm error

### ISSUE THREAD

**Issue by jackieron** [LeonardLaszlo/nw.js-armv7-binaries#11]
jack@jack-VirtualBox:~/nwjs/src$ python build/gyp_chromium -Goutput_dir=out_gn_arm -I third_party/node-nw/build/common.gypi third_party/node-nw/node.gyp
Updating projects from gyp files...
gyp: name 'arm_version' is not defined while evaluating condition 'arm_version==7 or arm_version=="default"' in v8/src/v8.gyp

jack@jack-VirtualBox:~/nwjs/src$ ninja -C out_gn_arm/nw nwjs
ninja: Entering directory `out_gn_arm/nw'
ninja: error: '../../build/util/LASTCHANGE', needed by 'obj/base/build_date.inputdeps.stamp', missing and no known rule to make it

how to  resolve it?

**Comment by LeonardLaszlo** [comment]
which version do you want to build?

**Comment by jackieron** [comment]
v0.21

**Comment by jackieron** [comment]
i want to build nwjs for arm9，i read the document of https://github.com/LeonardLaszlo/nw.js-armv7-binaries/blob/master/docs/build-nwjs-v0.21.x.md
and i want to know where and how to define arm version

**Comment by LeonardLaszlo** [comment]
Check the following file: `/nwjs/src/third_party/node-nw/build/common.gypi`

It has 2 line like:

```
# Set ARM architecture version.
'arm_version%': 7,
```

I am not sure if this is the only point where you have to change the version, but it is a good starting point.
