### ISSUE TITLE
Can you help me to build an arm version 

### ISSUE THREAD

**Issue by jackieron** [LeonardLaszlo/nw.js-armv7-binaries#12]
Hello, I am in China, can not be normal access Google source, so can't normal download chromium source code, can you please help me to compile a arm version of nw,js, thank you very much.

**Comment by jackieron** [comment]
Because of the company to develop software system on the arm, so I really need a arm version, nearly a month since I've been trying to compile the arm version, but source download properly all the time. My progress has been severely affected, and I might be punished by my boss if I go on like this, .I am very sincere to ask fro you help. Loyal thanks.

**Comment by LeonardLaszlo** [comment]
https://github.com/LeonardLaszlo/nw.js-armv7-binaries/releases
