### ISSUE TITLE
New Nw.js Builds

### ISSUE THREAD

**Issue by AndrejaN** [LeonardLaszlo/nw.js-armv7-binaries#13]
Hi Leonard, could you inform me when will the next build 0.22 and 0.23 will be available on your repository? I need them for my Pi3.

**Comment by LeonardLaszlo** [comment]
Hi, I'll let you know!

**Comment by jtg-gg** [comment]
@LeonardLaszlo 
you can try 23.5 from my repo :)
I skipped 22.x (my repo only works for 22.0 if you want to make 0.22 build)

**Comment by AndrejaN** [comment]
I'm trying to solve this error while trying to build PT for by Pi3.
I'm trying to build your development branch for ARM platform for my Raspbery Pi3 and only NW.js ARMv7 v0.21.6 are available at this moment., i think i have to use the latest 0.23.5 version, but they don't have for ARM platform i have to wait for https://github.com/LeonardLaszlo/nw.js-armv7-binaries/releases to compile the latest version.
I have built, but some error regarding the SSL3 protocol have been an issue for my Raspbery Pi3.
The same compiled version works on Windows with NW.js v0.21.6, but not in RaspPi3. That's strange.

![27760658-372d6b00-5e4d-11e7-9663-65c8da442015](https://user-images.githubusercontent.com/17863576/27786806-ef28443c-5fe2-11e7-93cb-cb10fa80a720.PNG)

and whit 0.20.6
![27761592-4387c8d4-5e5f-11e7-8d95-1f2cd736defc](https://user-images.githubusercontent.com/17863576/27786814-f55cb220-5fe2-11e7-8aff-29f3f0bfb6e2.PNG)

The connection is not https, and the error is still there. Compiled ver. on windows works fine, the problem is the ARM build of the NW.

**Comment by LeonardLaszlo** [comment]
@jtg-gg came up with a fix for this issue. Check https://github.com/LeonardLaszlo/nw.js-armv7-binaries/issues/7

**Comment by AndrejaN** [comment]
That's great. As i understand these are source i have to build them. Is it possible @LeonardLaszlo repository to be updated with new nw.js sdk binaries for arm soon?

**Comment by LeonardLaszlo** [comment]
Maybe next week or in 2 weeks... Now I have a lot of work to do and I don't really have time to build NW.js

**Comment by LeonardLaszlo** [comment]
Check the releases.

**Comment by rista86** [comment]
Hey @LeonardLaszlo is there any chance to build the new version? I need at least chromium 60+ because of some additional flag settings and that is from version 0.24.x.
Thank you in advance!

**Comment by LeonardLaszlo** [comment]
Hi! I am very busy lately and I would recomend you to build it yourself based on the tutorials in this repo!

**Comment by LeonardLaszlo** [comment]
@rista86 https://github.com/LeonardLaszlo/nw.js-armv7-binaries/releases/tag/v0.24.5

**Comment by rista86** [comment]
Thank you very much @LeonardLaszlo !

**Comment by LeonardLaszlo** [comment]
You are welcome!

**Comment by LeonardLaszlo** [comment]
https://github.com/LeonardLaszlo/nw.js-armv7-binaries/releases/tag/v0.26.6
