### ISSUE TITLE
Add non-SDK builds to releases

### ISSUE THREAD

**Issue by jrd261** [LeonardLaszlo/nw.js-armv7-binaries#15]
Hi Leonard. Thanks for all your work! For certain installations we'd like ARM builds that don't have the SDK in them.

**Comment by LeonardLaszlo** [comment]
I added a demo build here:
https://github.com/LeonardLaszlo/nw.js-armv7-binaries/releases/tag/v0.23.7

**Comment by LeonardLaszlo** [comment]
Something is not right, because the file size is almost the same

**Comment by LeonardLaszlo** [comment]
https://github.com/LeonardLaszlo/nw.js-armv7-binaries/releases/tag/v0.26.6
