### ISSUE TITLE
libgmodule-2.0.so.0 missing

### ISSUE THREAD

**Issue by Programming4life** [LeonardLaszlo/nw.js-armv7-binaries#17]
Keep getting this error:
`./nw: error while loading shared libraries: libgmodule-2.0.so.0: cannot open shared object file: No such file or directory`

The package libglib2.0-0 is installed.

**Comment by LeonardLaszlo** [comment]
Which version do you use?

**Comment by LeonardLaszlo** [comment]
Closing this issue because the lack of additional infos
