### ISSUE TITLE
Updating ffmpeg 

### ISSUE THREAD

**Issue by edelciomolina** [LeonardLaszlo/nw.js-armv7-binaries#18]
Hi,
Anyone can help to update the ffmpeg to run mp4 videos?
I tried using the linux 32 (libffmpeg.so) from https://github.com/iteufel/nwjs-ffmpeg-prebuilt/releases into RaspPI, but the NW crashs.

Change the libffmpeg.so is the better way or is there another way to fix it.

Thank you!

**Comment by LeonardLaszlo** [comment]
Hi,

you can play mp4 videos using the 'chrome branding' archives from releases.
