### ISSUE TITLE
[Question] OpenMAX support for HW accelerated video playback

### ISSUE THREAD

**Issue by psevestre** [LeonardLaszlo/nw.js-armv7-binaries#20]
Hi there.

I´m trying to use NW-ARM (Chrome Branding) on a Raspberry B+ and, most parts, it works like a charm. 

The only issue I´m facing is when I try to play H.256 encoded videos using a regular "<video>" tag: the playback is very choppy, which would be a showstopper for my app.

The very same video plays smoothly using omxplayer, so I´m guessing the embedded ffmpeg library does not support OpenMAX and/or somehow is not detecting the required libraries.

What can I do in order to enable OpenMAX video playback with NWJS ?

TIA,

**Comment by LeonardLaszlo** [comment]
This repo is not the official NW.js repo. Here you can find docs to make experimental builds of NW.js for ARM linux devices. I know your question is somehow related to the ARM version but I cannot really help you to find a solution.

I think you have better chances to find the answer for your question on the official NW.js project repo.

For the official repo please visit: https://github.com/nwjs/nw.js
