### ISSUE TITLE
NW.js ARMv7 v0.27.6 non-SDK build seems to contain devtools

### ISSUE THREAD

**Issue by NorbarTDB** [LeonardLaszlo/nw.js-armv7-binaries#22]
Hi there! Thanks very much for creating these builds, they're very useful!

One thing I noticed though, was on the aforementioned build (NW.js ARMv7 v0.27.6) while it does lack SDK elements like nwjc, devtools seems to be included? 

I was under the impression that the standard flavour of NWJS did not include devtools, is this not the case or is it a configuration issue with this build?

I don't believe it is world-ending or anything since it's possible to disable devtools via the manifest file, just thought it ought to be mentioned (if, indeed, it's unintentional).

Many thanks for your time!

**Comment by LeonardLaszlo** [comment]
I probably added dev tools by mistake. For future versions it will not be included.
