### ISSUE TITLE
When building latest releases of NW.js for ARM builds fail mostly at the linking step

### ISSUE THREAD

**Issue by LeonardLaszlo** [LeonardLaszlo/nw.js-armv7-binaries#26]
@jtg-gg Could you take a look at why do builds on latest versions fail after applying your patches for arm builds?

**Comment by jtg-gg** [comment]
what is the error message?
anyway I am using debian-jessie sysroot, chromium build script doesn't provide this anymore
but if you are not cleaning your build, you should still have this debian-jessie sysroot

**Comment by LeonardLaszlo** [comment]
when did the chromium build script stopped to provide debian-jessie sysroot?

**Comment by jtg-gg** [comment]
https://github.com/nwjs/chromium.src/commit/015a8b82b8e1b1e75421f46d8a969e443a0fedfb

looks like jessie last supported in  nw28

I don't have any arm board, so I am dependent on qemu arm emulator, which still using debian jessie
If I build using the latest "sid" I can't test it in the emulator

**Comment by jtg-gg** [comment]
thx for the offer, but the shipping cost might not worth doing
anyway I don't have time / resources for this public build

**Comment by LeonardLaszlo** [comment]
Hi @jtg-gg, when I try to build nw28 with the building script in the root of the repo (`building-script.sh`, commit: aafb1792eabcca9b5d425aeefb6b2f2c1ec4fb54) I get the following error:
https://gist.github.com/LeonardLaszlo/b454df742306d9f2a8fe93991b9f6cbf

Can you help me to find out what's going on here?

**Comment by jtg-gg** [comment]
not sure, why are you getting this
../../third_party/node-nw/deps/openssl/openssl/crypto/arm_arch.h:46:6: error: #error "unsupported ARM architecture"
# error "unsupported ARM architecture"

I suggest skip nw28, If I am not wrong I skipped the last version, was catching up with nw29

**Comment by julientype** [comment]
[504/1243] CC obj/third_party/node-nw/deps/openssl/openssl/crypto/md5/openssl.md5_dgst.o
In file included from ../../third_party/node-nw/deps/openssl/openssl/crypto/md5/md5_locl.h:98:0,
                 from ../../third_party/node-nw/deps/openssl/openssl/crypto/md5/md5_dgst.c:60:
../../third_party/node-nw/deps/openssl/openssl/crypto/md5/md5_dgst.c: In function ‘md5_block_data_order’:
../../third_party/node-nw/deps/openssl/openssl/crypto/md32_common.h:276:75: warning: right-hand operand of comma expression has no effect [-Wunused-value]
 #    define HOST_c2l(c,l)        ((l)=*((const unsigned int *)(c)), (c)+=4, l)

----- your variables are not declared correctly  a typo error ------ 
md5_locl.h:98:0
----line 98
openssl.md5_dgst.o
is calling  it.....  typo error

**Comment by LeonardLaszlo** [comment]
Not relevant anymore.
