### ISSUE TITLE
How to use nw-js-symbol-0.15.1-linux-arm7.tar.gz?

### ISSUE THREAD

**Issue by guddu313** [LeonardLaszlo/nw.js-armv7-binaries#29]
Hi LeonardLaszlo,

I want to debug the nw application. So i wanted to know how I can integrate nw-js-symbol-0.15.1-linux-arm7.tar.gz for it?

Regards,
Guddu

**Comment by LeonardLaszlo** [comment]
Sorry Guddu, I don't know. If you want to debug NW.js maybe you should contact developers of the project. Probably they can give you more support.
