### ISSUE TITLE
Trying to compile Nw.js 0.15.1

### ISSUE THREAD

**Issue by guddu313** [LeonardLaszlo/nw.js-armv7-binaries#30]
Hi LeonardLaszlo,

I am trying to compile Nw.js version 0.15.1 but i am facing below issues.
(1) I am not able to find nw15 branch for v8/src.
cd $NWJS/src/v8
git checkout nw15
(2) Below patches are not available
wget https://raw.githubusercontent.com/LeonardLaszlo/nw.js-armv7-binaries/master/patches/0001.patch -P $NWJS/
wget https://raw.githubusercontent.com/LeonardLaszlo/nw.js-armv7-binaries/master/patches/0006.patch -P $NWJS/
wget https://raw.githubusercontent.com/LeonardLaszlo/nw.js-armv7-binaries/master/patches/0003.patch -P $NWJS/ 

Can you please help me regarding this?
Any help is appreciable.
Regards,
Pravin

**Comment by LeonardLaszlo** [comment]
Why don't you try to build a newer version?

**Comment by LeonardLaszlo** [comment]
I am sorry, but I cannot really help with this.
There are many useful tips and tricks under the docs directory in case you want to give it a shot.
