### ISSUE TITLE
Trying to compile Nw.js 0.27.x

### ISSUE THREAD

**Issue by guddu313** [LeonardLaszlo/nw.js-armv7-binaries#31]
I am able to build nwjs but when i am building node then i am getting below error.

ninja: Entering directory `out_gn_arm/Release'
[1/1] SOLINK lib/libnode.so
FAILED: lib/libnode.so lib/libnode.so.TOC
if [ ! -e lib/libnode.so -o ! -e lib/libnode.so.TOC ]; then ../../third_party/llvm-build/Release+Asserts/bin/clang++ -shared -Wl,-z,now -Wl,-z,relro -Wl,--fatal-warnings -Wl,-z,defs -pthread -Wl,-z,noexecstack -fPIC -B/home/mgp/Pravin/Nw-js/nwjs/src/third_party/binutils/Linux_x64/Release/bin -L../nw/lib/ -lnw ../nw/obj/buildtools/third_party/libc++/libc++/*.o ../nw/obj/buildtools/third_party/libc++abi/libc++abi/*.o ../nw/obj/buildtools/third_party/libunwind/libunwind/*.o -pthread -target arm-linux-gnueabihf --sysroot=/home/mgp/Pravin/Nw-js/nwjs/src/build/linux/debian_jessie_arm-sysroot -Wl,-O1 -Wl,--as-needed -Wl,--gc-sections -Wl,--no-as-needed -lpthread -Wl,--as-needed -o lib/libnode.so -Wl,-soname=libnode.so @lib/libnode.so.rsp && { readelf -d lib/libnode.so | grep SONAME ; nm -gD -f p lib/libnode.so | cut -f1-2 -d' '; } > lib/libnode.so.TOC; else ../../third_party/llvm-build/Release+Asserts/bin/clang++ -shared -Wl,-z,now -Wl,-z,relro -Wl,--fatal-warnings -Wl,-z,defs -pthread -Wl,-z,noexecstack -fPIC -B/home/mgp/Pravin/Nw-js/nwjs/src/third_party/binutils/Linux_x64/Release/bin -L../nw/lib/ -lnw ../nw/obj/buildtools/third_party/libc++/libc++/*.o ../nw/obj/buildtools/third_party/libc++abi/libc++abi/*.o ../nw/obj/buildtools/third_party/libunwind/libunwind/*.o -pthread -target arm-linux-gnueabihf --sysroot=/home/mgp/Pravin/Nw-js/nwjs/src/build/linux/debian_jessie_arm-sysroot -Wl,-O1 -Wl,--as-needed -Wl,--gc-sections -Wl,--no-as-needed -lpthread -Wl,--as-needed -o lib/libnode.so -Wl,-soname=libnode.so @lib/libnode.so.rsp && { readelf -d lib/libnode.so | grep SONAME ; nm -gD -f p lib/libnode.so | cut -f1-2 -d' '; } > lib/libnode.so.tmp && if ! cmp -s lib/libnode.so.tmp lib/libnode.so.TOC; then mv lib/libnode.so.tmp lib/libnode.so.TOC ; fi; fi
clang: error: no such file or directory: '../nw/obj/buildtools/third_party/libunwind/libunwind/*.o'
ninja: build stopped: subcommand failed.

Actually on this path "'_../nw/obj/buildtools/third_party/libunwind/libunwind/*.o_" there is no libunwind.
gn also not generating ninja file for libunwind.

Can anyone help me regarding this?
Any help would be appreciable.

Regads,
Guddu

**Comment by LeonardLaszlo** [comment]
Hi there, for older builds you can take a look at this https://gist.github.com/llamasoft/33af03b73945a84d7624460d67b922ab

Otherwise for newer builds check the Release tab.
