### ISSUE TITLE
the project died?

### ISSUE THREAD

**Issue by jamilservicos** [LeonardLaszlo/nw.js-armv7-binaries#32]
the project died?
because it stopped in version 28 and is already already in 37.

**Comment by LeonardLaszlo** [comment]
Hi @jamilservicos. The short answer is yes.

The long answer is that I do not have the time and the resources to maintain this project anymore. If you want to contribute to this project any contributions are always welcomed!

**Comment by wittend** [comment]
I would be interested to know what resources and level of commitment is
required to keep these builds up to date.  I would consider contributing to
this effort if I can do it properly.

Dave

**Comment by jonwwilkes** [comment]
@wittend Requirements would be the same as for building Chromium: an x64_64 box with > 100MB harddrive space and > 16GB ram running (apparently) Ubuntu 14.04.

**Comment by jonwwilkes** [comment]
@LeonardLaszlo Does your "building-script.sh" in this repo do the work of setting up the cross-compiling environment for the user? Or is that already supposed to be set up before running the script?

**Comment by julientype** [comment]
here here..... i can help in the test side.....  
i have a banana pi board.....  
tried electron no go...... yours did ver---- 28

**Comment by Elvincth** [comment]
Please continue, you really saved my life

**Comment by jonwwilkes** [comment]
@LeonardLaszlo Had a look at the script.

Why are there patches being applied to chromium from chromium.src? I thought Chromium already runs on arm.

Additionally, from what I can tell _none_ of the nw patches apply cleanly. So it appears I'd have to manually patch every single patch to the nw.js codebase. I'll ask Roger if he's interested in merging in those patches upstream. If not then I have no interest in working on a separate unmaintainable branch.

**Comment by NorbarTDB** [comment]
@jonwwilkes while looking for updates I think I stumbled across your request to Roger on Google Groups (https://groups.google.com/d/msg/nwjs-general/j5ZCEf1qnIE/bg7_5p--BwAJ); did you ever hear back on that? Did the patches get merged?

**Comment by NbrTDB** [comment]
@jonwwilkes I did not have problems applying patches, except insofar as all attempts to use curl/wget for the Github URLs wound up with redirects to the login page (and it wouldn't authenticate either). Once I manually downloaded them they seem to apply fine for nw28.

**Comment by NbrTDB** [comment]
@LeonardLaszlo no wonder you abandoned this, I'm trying to build nw28 and completely losing the will to live, haha!

It looks like some ARM patches are floating around @jtg-gg's dev branches (like dev42-m78: https://github.com/jtg-gg/node-webkit/compare/dev42-m78); do you reckon we'd have an easier time trying to get nw42 to build? You got any pointers for people trying to figure this out on their own? For instance I'm interested to know how you arrived at the list of ARM patches in the first place.

**Comment by LeonardLaszlo** [comment]
Back then I had much more time to work on this. I could not have make the builds without the help of @jtg-gg  and some other people.

**Comment by TagLoomis** [comment]
I really appreciate the work you've done!

It's sad the nwjs team isn't stepping up to support Arm yet.

But I wager it will happen at some point in the future.

**Comment by NbrTDB** [comment]
I understand. Well I must say, I'm very grateful for all the time and effort you put into it while you could; you were a lifesaver!

Hahaha, and literally as I write this, @TagLoomis jumps in with the same sentiment, I see! 

I agree, I'm kind of surprised armhf support isn't a bigger deal for the team as there's so many potential applications for running NW.js on little arm devices.

My understanding is that everyone's time to work on other builds is very limited (understandable!) particularly variants that are seen as niche, but could it be that the demand for arm is not observed because, in lieu of any support, people are simply finding alternative solutions?

**Comment by NbrTDB** [comment]
@LeonardLaszlo you _legend_, I spotted the new 0.44.3 build you released in March! Just want to express my gratitude for you taking another look at this.

I appreciate the binaries are not tested so am proceeding cautiously, but so far can happily report I have encountered no issues with either the SDK nor the standard (non-ffmpeg) builds. Thanks very much!

I seem to recall (per #24) one of the problems was it was awkward getting builds to succeed for newer versions. Has something changed about the NW.js project or its components that made it possible to put together a build again in newer versions, or are there just different steps to take? Is it now possible to follow the current build instructions successfully (https://github.com/LeonardLaszlo/nw.js-armv7-binaries/blob/master/docs/build-nwjs-v0.28.x.md) if we want to produce our own builds for 0.44.x?

**Comment by LeonardLaszlo** [comment]
Hello Sir, thanks for the kind words.

I am not sure what happened with the NW.js projects recently, but nowadays it is quite easy to build it for ARM.

The last build was done as described by the Dockerfile in the root of the repo.

There are 2 bash scripts used:
- build-container.sh to build the docker image (also available on docker hub https://hub.docker.com/r/laslaul/nwjs-arm-build-env)
- build-nwjs.sh to build NW.js

You can give it a try and maybe build a newer version. It takes a lot of time to build completely, but if you have a super computer you can give it a try.

**Comment by julientype** [comment]
ahhhh the  legend is back.......
try and use it as a programmer calling card....
you network with others this way....   you maintain 1 component..... 10% time one component and 90% one anything else payable.... a calling card..

**Comment by LeonardLaszlo** [comment]
If you guys need to build an older version you can take a look here:
https://gist.github.com/llamasoft/33af03b73945a84d7624460d67b922ab

Might be really useful. Cheers!

**Comment by julientype** [comment]
chat code and your return investment over time no one id asking you to work 24h a day at 0$ ...your networking,,,, code chat work to survive....
i go out and play bass ball and work.... leverage you talent and time over time  and your network grows..... whee more clients give money for your talents .. they want now 
building a network    takes years..... yet when you peek it explodes to millions
and they all want instent buges seved to hie clients
