### ISSUE TITLE
How to replace the libffmpeg.so?

### ISSUE THREAD

**Issue by zzxzzk115** [LeonardLaszlo/nw.js-armv7-binaries#33]
I need to play a mp3 format audio in my nw.js project... 
at https://github.com/iteufel/nwjs-ffmpeg-prebuilt I didn't find an arm-linux version.
What should I do?

**Comment by mauritslamers** [comment]
I solved this by using mpg123 and require('child_process').spawn.

**Comment by mauritslamers** [comment]
Just curious, is using the WebAudio API not an option?

**Comment by LeonardLaszlo** [comment]
Closed because no reply.
