### ISSUE TITLE
How to compile Nw.js 0.36.4 ?

### ISSUE THREAD

**Issue by wu6692776** [LeonardLaszlo/nw.js-armv7-binaries#36]
This seems to be the last version to access the chrome.serial object

**Comment by LeonardLaszlo** [comment]
Hello Sir, you can start from https://github.com/LeonardLaszlo/nw.js-armv7-binaries/blob/master/docs/build-nwjs-v0.28.x.md 

Have a great day,
Leonard.

**Comment by LeonardLaszlo** [comment]
Please checkout https://gist.github.com/llamasoft/33af03b73945a84d7624460d67b922ab
I think the patches won't apply automatically, but if you apply them manually you can probably build any version with cross compilation.

Thanks to @llamasoft we can now build newer versions.

**Comment by LeonardLaszlo** [comment]
Also I recommend to use a virtual machine of a docker container. 
You don't want to mess up your machine.

**Comment by wu6692776** [comment]
Thanks for your support, I will try these later, if I succeed, I will post it here.
