### ISSUE TITLE
Invalid cross-device link while using automatic build

### ISSUE THREAD

**Issue by pleasantone** [LeonardLaszlo/nw.js-armv7-binaries#40]
Build host is ubuntu 20.04 amd64, obviously with docker installed.

Checked out branch in the container is --nw48-- and the desired branch is --nw49--
Checking out nw49 branch
Checkout branch: nw49
Cloning into '/usr/docker/nwjs/src/content/nw'...
remote: Enumerating objects: 2013, done.
remote: Counting objects: 100% (2013/2013), done.
remote: Compressing objects: 100% (1641/1641), done.
remote: Total 2013 (delta 369), reused 1388 (delta 240), pack-reused 0
Receiving objects: 100% (2013/2013), 59.08 MiB | 29.10 MiB/s, done.
Resolving deltas: 100% (369/369), done.
Checking out files: 100% (1812/1812), done.
Cloning into '/usr/docker/nwjs/src/third_party/node-nw'...
remote: Enumerating objects: 29077, done.
remote: Counting objects: 100% (29077/29077), done.
remote: Compressing objects: 100% (23982/23982), done.
remote: Total 29077 (delta 7093), reused 12086 (delta 4195), pack-reused 0
Receiving objects: 100% (29077/29077), 70.15 MiB | 8.29 MiB/s, done.
Resolving deltas: 100% (7093/7093), done.
Checking out files: 100% (29523/29523), done.
Cloning into '/usr/docker/nwjs/src/v8'...
remote: Enumerating objects: 12813, done.
remote: Counting objects: 100% (12813/12813), done.
remote: Compressing objects: 100% (9595/9595), done.
remote: Total 12813 (delta 4309), reused 6234 (delta 3013), pack-reused 0
Receiving objects: 100% (12813/12813), 27.46 MiB | 6.93 MiB/s, done.
Resolving deltas: 100% (4309/4309), done.
[P87 20:47:45.467 fs.go:449 W] fs: failed to rename directory "/usr/docker/depot_tools/.cipd_bin/.cipd/pkgs/6/GJZUS6J7KEX1biMDc2u_hWyYk8IUvcyUqsfS773LKgUC" - rename /usr/docker/depot_tools/.cipd_bin/.cipd/pkgs/6/GJZUS6J7KEX1biMDc2u_hWyYk8IUvcyUqsfS773LKgUC /usr/docker/depot_tools/.cipd_bin/.cipd/pkgs/6/XZZ2p6FeF8ne: invalid cross-device link

**Comment by LeonardLaszlo** [comment]
I am getting those errors sometimes as well.
What's weird for me is that the .cipd_bin is usually under the `/usr/docker/nwjs` directory and the logs seems to be located under `/usr/docker/depot_tools`.

**Comment by LeonardLaszlo** [comment]
Please try again with the latest version of my script.

**Comment by LeonardLaszlo** [comment]
I am also getting:

```
[P55 07:45:48.708 fs.go:449 W] fs: failed to rename directory "/usr/docker/depot_tools/.cipd_bin/.cipd/pkgs/6/GJZUS6J7KEX1biMDc2u_hWyYk8IUvcyUqsfS773LKgUC" - rename /usr/docker/depot_tools/.cipd_bin/.cipd/pkgs/6/GJZUS6J7KEX1biMDc2u_hWyYk8IUvcyUqsfS773LKgUC /usr/docker/depot_tools/.cipd_bin/.cipd/pkgs/6/WVH8yEsgZdf9: invalid cross-device link
```

These are only some warnings. You can ignore then.
