### ISSUE TITLE
Signal 11 Fault

### ISSUE THREAD

**Issue by chrisgaeth** [LeonardLaszlo/nw.js-armv7-binaries#44]
When installing and attempting to run on Pi400, Ubuntu 21.04, executing
./nw --use-gl=egl --ignore-gpu-blacklist --disable-accelerated-2d-canvas --num-raster-threads=2  results in;

Failed to generate minidump.Received signal 11 SEGV_MAPERR 00005efa259e
[end of stack trace]
Calling _exit(1). Core file will not be generated.

Not sure where to troubleshoot from here.

**Comment by LeonardLaszlo** [comment]
Hello @chrisgaeth,

Pi400 has a 1.8GHz Quad core ARM Cortex-A72 CPU with ARMv8-A architecture.
This repository provides only the binary for the ARMv7 architecture.
https://en.wikipedia.org/wiki/ARM_Cortex-A72

If you are willing to spend some time on this, there was somebody who managed to build the ARMv8 binaries based on this repository. Take a look at the closed PRs and you will find it.
https://github.com/LeonardLaszlo/nw.js-armv7-binaries/issues/16

If you manage to adapt the building scripts to build also the ARMv8 version please send me a PR.

I hope this will help you.
