### ISSUE TITLE
High load

### ISSUE THREAD

**Issue by exander77** [LeonardLaszlo/nw.js-armv7-binaries#5]
Is it possible that nw has much higher load than Firefox or Google Chrome? I just tested it as a replacement of Firefox in my kiosk and running simple JavaScript weather animation it has load 3.5, with Firefox it is 0.86, with Google Chrome it was something similar to Firefox if I remember correctly.

**Comment by LeonardLaszlo** [comment]
It might be, but it should not have higher load than Chromium.

Please try with other versions and let me know if you have higher load on each version.

Posting more information about the environment you are using, logs, version of nw and os would have been useful.

**Comment by exander77** [comment]
I tested Chromium, it has load cca 1.4.

So:
Chromium: 1.4
Iceweasel.: 0.86
nw.js: 3.5

It is amost clean Raspbian Jessie Lite (2016-11-25-raspbian-jessie-lite) with xorg and matchbox only. Icewasel, Chromium or nw.js are only x programs running, they are launched by xinitrc. No additional programs are running.

**Comment by LeonardLaszlo** [comment]
can you post the parameters you run NW with and the logs?
