### ISSUE TITLE
Skia shader compilation error

### ISSUE THREAD

**Issue by prominentdetail** [LeonardLaszlo/nw.js-armv7-binaries#50]
I am running an app that uses three.js and I receive these errors when it tries to render. I can't seem to find any answers from anyone why this is occurring. Maybe it is related to nw.js?

`
[2122:2122:1101/195735.880642:ERROR:shared_context_state.cc(73)] Skia shader compilation error
-----------------
#version 110

uniform sampler2D uTextureSampler_0_Stage0;
varying vec2 vlocalCoord_Stage0;
void main() {
    vec4 outputColor_Stage0 = vec4(1.0);
    vec2 texCoord;
    texCoord = vlocalCoord_Stage0;
    outputColor_Stage0 = texture2D(uTextureSampler_0_Stage0, texCoord);
    {
        gl_FragColor = outputColor_Stage0;
    }
}

Errors:
0:1(10): error: GLSL 1.10 is not supported. Supported versions are: 1.00 ES, 3.00 ES, and 3.10 ES
`

**Comment by LeonardLaszlo** [comment]
In my understanding of the error message Skia uses open gl 1.10 features, but the only supported versions are:
1.00 ES, 3.00 ES, and 3.10 ES
I am afraid there is not much we can do on nw.js side in order to fix this.

**Comment by prominentdetail** [comment]
Okay, thanks for the help. I'll try to prod the three.js community for more info.
