### ISSUE TITLE
will the arm64 version support sdk again in the future?

### ISSUE THREAD

**Issue by honxinn** [LeonardLaszlo/nw.js-armv7-binaries#58]
may i ask if there are any plans to continue supporting the sdk version in the future?
It would be fantastic if support continues. :)

**Comment by honxinn** [comment]
the version I'm currently using is still 0.23.7, which comes with sdk, but its support for new JavaScript features is very poor, and this has been quite frustrating for me. Additionally, I frequently open DevTools for debugging in my work, so this limitation forces me to stick to this version. If a new version with SDK support could be provided in the future, it would be truly amazing.

**Comment by LeonardLaszlo** [comment]
Life is happening and I don't have time anymore to take care of this project.

**Comment by honxinn** [comment]
> Life is happening and I don't have time anymore to take care of this project.

Well, good luck
