### ISSUE TITLE
OpenSSL issue

### ISSUE THREAD

**Issue by LeonardLaszlo** [LeonardLaszlo/nw.js-armv7-binaries#7]
There is a problem with the OpenSSL in ARMv7 builds.
When I run something like:

```
var request = require('request');

request('https://www.google.com', function (error, response, body) {
  console.log('error:', error); // Print the error if one occurred
  console.log('statusCode:', response && response.statusCode); // Print the response status code if a response was received
  console.log('body:', body); // Print the HTML for the Google homepage.
});
```

I get the following error:

```
error: Error: write EPROTO 2970357760:error:1006706B:elliptic curve routines:ec_GFp_simple_oct2point:point is not on curve:../../third_party/node/deps/openssl/openssl/crypto/ec/ecp_oct.c:417:
2970357760:error:1408D132:SSL routines:ssl3_get_key_exchange:bad ecpoint:../../third_party/node/deps/openssl/openssl/ssl/s3_clnt.c:1875:


    at exports._errnoException (util.js:1022:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:804:14)
```

@jtg-gg Any idea what is wrong?

**Comment by jtg-gg** [comment]
@LeonardLaszlo I am not sure, FYI this arm build was experimental, we are not using this yet in our daily build, so I can't help you to debug run time error :(

**Comment by LeonardLaszlo** [comment]
Here I've found some additional information about the problem:

https://github.com/Microsoft/openssl/commit/68886be7e2cd395a759fcd41d2cede461b68843d

**Comment by gizmopt** [comment]
Hello @LeonardLaszlo I experiencing this problem too, I tried different versions and have always the same issue. I tried to use the version 22 but it gives-me an error like you reference on the issue https://github.com/LeonardLaszlo/nw.js-armv7-binaries/issues/9

With this ported version https://github.com/jalbam/nwjs_rpi I don't have this problem but have others due to the old version its on it.

Any ideas? I really need to use nw with an Rpi3
Thank's.

**Comment by LeonardLaszlo** [comment]
Well we need some enthuziast developer, who is able to debug Chromium and it's dependencies. Unfortunately I cannot help with that...

**Comment by jtg-gg** [comment]
@LeonardLaszlo I've "fixed" the openssl issue, by disabling openssl assembly files
I am currently testing it on nw24 beta, will patch nw23 later, I'll update you once I am done

**Comment by LeonardLaszlo** [comment]
thank you!

**Comment by jtg-gg** [comment]
Apply these 3 patches on top of original **nwjs/chromium.src** repository
![screen shot 2017-07-07 at 11 46 12 am](https://user-images.githubusercontent.com/4043527/27981893-c1174fa4-63be-11e7-9409-06f580b89d9b.png)

Apply these 3 patches on top of original **nwjs/nw.js** repository
![screen shot 2017-07-07 at 11 47 54 am](https://user-images.githubusercontent.com/4043527/27981894-c11b854c-63be-11e7-97f7-ce59e85a4978.png)

if you curious, this is the actual node.js openssl patch that "fix" the https connection problem
https://github.com/jtg-gg/node-webkit/commit/27537f1b8563b805eec1b3e327296a824cdd5f79#diff-63fcc6b9d8ae5bba928e573d8340e3c3

**Comment by LeonardLaszlo** [comment]
Fixed with release: NW.js ARMv7 v0.24.5
