### ISSUE TITLE
Building NW.js v0.22.x fails

### ISSUE THREAD

**Issue by LeonardLaszlo** [LeonardLaszlo/nw.js-armv7-binaries#9]
```
leonard@leonard:~/nwjs/src$ python build/gyp_chromium -Goutput_dir=out_gn_arm -I third_party/node-nw/build/common.gypi third_party/node-nw/node.gyp
Updating projects from gyp files...
gyp: Undefined variable OBJ_DIR in third_party/node-nw/node.gyp
```

**Comment by LeonardLaszlo** [comment]
Running:

```
leonard@leonard:~/nwjs/src$ grep -rnw third_party/node-nw/build/*.gypi -e "OBJ_DIR"
```

produces no output.

**Comment by jtg-gg** [comment]
@LeonardLaszlo make sure the git repo are pointing to the correct branch / commit
then run the "gclient runhooks" to apply the patches
then try again the gyp_chromium

btw I am currently busy with something else, my repo only up to date to nw22.1

**Comment by LeonardLaszlo** [comment]
You are right! It works with nw22.1, but any older version is not working yet! Thanks for your help!

Please let me know when you update it to be compatible with newer versions!

**Comment by LeonardLaszlo** [comment]
skipped release of NW.js v0.22.x
